### ISSUE TITLE
[SRACH]

### ISSUE THREAD

**Issue by mlasy** [terafoundation/wallet#14]
Hey, 

Why are there executables in this git?

**Comment by djKooks** [comment]
I also think it is better to remove executable files in repos. Seems it needs some arrangement...

**Comment by dashed** [comment]
Probably a scam. 😆 

<img width="1340" alt="screen shot 2019-02-05 at 2 31 28 am" src="https://user-images.githubusercontent.com/139499/52258717-29324a80-28ee-11e9-9bdf-aebc4d2a30b9.png">

**Comment by djKooks** [comment]
Yeah... I replied on mail, and said that mail address cannot be found...

**Comment by cmjagtap** [comment]
I also got the same mail

**Comment by visi27** [comment]
Definitely a scam. The same email was sent to me from the same sender but by a different address. Check the screeenshot and compare it to  @dashed response.
![screenshot from 2019-02-05 09-03-57](https://user-images.githubusercontent.com/6974384/52260071-31f24300-2925-11e9-87a8-50c401adbf99.png)

**Comment by DavidBruchmann** [comment]
![image](https://user-images.githubusercontent.com/999146/52260599-30db0900-2959-11e9-9c38-a5b4ad5fb46a.png)

**Comment by DavidBruchmann** [comment]
Just an assumption:
Are all of you subscribed to (scam) TeraBox (terabox.me)?

**Comment by dhamaniasad** [comment]
![image](https://user-images.githubusercontent.com/4560482/52261406-4814f900-294f-11e9-98d0-78f32abdac19.png)

**Comment by visi27** [comment]
> Just an assumption:
> Are all of you subscribed to (scam) TeraBox (terabox.me)?

No, this is the first time I hear about this. Pure spam

**Comment by dashed** [comment]
@DavidBruchmann pretty sure all our emails from GitHub got mined 😄 .

**Comment by AFlowers00** [comment]
@mlasy @djKooks @dashed @cmjagtap @visi27 @DavidBruchmann Hey everyone, I would like to address to two things here;

1.

I admit the email campaigns are not really beautiful and our email addresses got closed by Gmail (due high volume) but project do needs help of developers and all of the emails that we've sent was genuine asking for help. All the emails have sent by volunteers, miners of this project.

2. 

There is nothing scammy it, .exe files indeed shouldn't take place yet it's a silly thing to say without fully researching the project. I get if you are pissed because of spamming, this shouldn't be the place to throw shit.

**Comment by AFlowers00** [comment]
@wyaeld You don't even know the CRM tool we have used. All email addresses get sent under one name and surname (and that name is the account owner's name).

So, let me understand. There is a project where more developer needed. Supporters of the project comes together and sends email. Whole email text is about explaining the project, how it needs developer and at the end of the email it mentions how to find the project.

You come here and find it. You are a **developer**, if you really know how to code you can read the codebase, check the links and make sure about it's legitimacy.

If the project would have scammed people by making shit promises, team would have tons of cash in it's safe and afford to acquire developers.

In here, we offer coins to compensate your work. You come here and take a shit on it. Nice.

Some of you really get butthurt just because of an email. Wow.

**Comment by terafoundation** [comment]
> Why are there executables in this git?

Why  not?

**Comment by terafoundation** [comment]
About spam. I have nothing to do with spam. I am against spam.

**Comment by wyaeld** [comment]
Renaming the issue to hide the criticism will likely not work.  There are 2 possibilities.

1) you are an honest developer, who decided to put opaque executables into a git repo and then message a bunch of random developers, despite executables being a massive red flag.  That would make you a complete idiot.

2) you are dishonest, the executable contain malware or some other method of compromising private keys, like so many attacks in this space.

Trustworthy developers build communities.

If I am wrong, then you can delete the executables and if there were important, include the build instructions to compile them.  Simple.

**Comment by AFlowers00** [comment]
@wyaeld Do you even checked out the executables? Those are windows exe files. No developer uses Windows.

Compiling the wallet and instructions are already on the main repo page.

I'm not the developer nor the part of the team. We want to support the project therefore we are reaching out developers to invite them here. Very simple.

**Comment by dashed** [comment]
@AFlowers00 what's your involvement with terafoundation? Looks like you just registered recently, and the email campaign looks suspiciously like a sabotage operation against terafoundation.

**Comment by AFlowers00** [comment]
No involvement. I'm not from the team and I'm not an outreach expert, therefore our plan to reach out developers might have done in a poor way. Simple as that.

**Comment by dhamaniasad** [comment]
> Supporters of the project comes together and sends email.

Which supporters are you talking about? Because I see all the commits in this repo having been made from a single account.

**Comment by AFlowers00** [comment]
@dhamaniasad Have you checked the explorer or even looked at the specs of the project? This is coin is mineable. There are over 1000 full node on the network, tons of miners from around the world. Supporter word there means miners.

**Comment by terafoundation** [comment]
Ok, close "СРАЧ"

P.S.
**I have nothing to do with spam**. I am against spam.

**Comment by wyaeld** [comment]
haha, everything deleted
